#pragma once

// @generated by torchgen/gen.py from NativeMetaFunctions.h

#include <ATen/core/Tensor.h>
#include <ATen/core/IListRef.h>
#include <ATen/TensorMeta.h>
#include <ATen/TensorIterator.h>

#include <ATen/ops/_adaptive_avg_pool2d_meta.h>
#include <ATen/ops/_adaptive_avg_pool2d_backward_meta.h>
#include <ATen/ops/_adaptive_avg_pool3d_meta.h>
#include <ATen/ops/_adaptive_avg_pool3d_backward_meta.h>
#include <ATen/ops/_add_batch_dim_meta.h>
#include <ATen/ops/_add_relu_meta.h>
#include <ATen/ops/_addmm_activation_meta.h>
#include <ATen/ops/_aminmax_meta.h>
#include <ATen/ops/_amp_foreach_non_finite_check_and_unscale_meta.h>
#include <ATen/ops/_amp_update_scale_meta.h>
#include <ATen/ops/_assert_async_meta.h>
#include <ATen/ops/_assert_tensor_metadata_meta.h>
#include <ATen/ops/_autocast_to_full_precision_meta.h>
#include <ATen/ops/_autocast_to_reduced_precision_meta.h>
#include <ATen/ops/_backward_meta.h>
#include <ATen/ops/_batch_norm_impl_index_meta.h>
#include <ATen/ops/_batch_norm_impl_index_backward_meta.h>
#include <ATen/ops/_cast_Byte_meta.h>
#include <ATen/ops/_cast_Char_meta.h>
#include <ATen/ops/_cast_Double_meta.h>
#include <ATen/ops/_cast_Float_meta.h>
#include <ATen/ops/_cast_Half_meta.h>
#include <ATen/ops/_cast_Int_meta.h>
#include <ATen/ops/_cast_Long_meta.h>
#include <ATen/ops/_cast_Short_meta.h>
#include <ATen/ops/_cdist_backward_meta.h>
#include <ATen/ops/_cdist_forward_meta.h>
#include <ATen/ops/_cholesky_solve_helper_meta.h>
#include <ATen/ops/_choose_qparams_per_tensor_meta.h>
#include <ATen/ops/_coalesce_meta.h>
#include <ATen/ops/_coalesced_meta.h>
#include <ATen/ops/_compute_linear_combination_meta.h>
#include <ATen/ops/_conj_meta.h>
#include <ATen/ops/_conj_copy_meta.h>
#include <ATen/ops/_conj_physical_meta.h>
#include <ATen/ops/_conv_depthwise2d_meta.h>
#include <ATen/ops/_convert_indices_from_coo_to_csr_m